import type { EntitySchema } from "../rag/types.js";

export const entitySchemas: Record<string, EntitySchema> = {
  message: {
    description: "Outlook mail message",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the message",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      subject: {
        type: "string",
        description: "Subject line of the message",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      body: {
        type: "object",
        description: "Body of the message (contentType + content)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      bodyPreview: {
        type: "string",
        description: "First 255 characters of the message body as plain text",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      from: {
        type: "object",
        description: "Sender of the message (emailAddress object)",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      toRecipients: {
        type: "array",
        description: "To: recipients of the message",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      ccRecipients: {
        type: "array",
        description: "Cc: recipients of the message",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      bccRecipients: {
        type: "array",
        description: "Bcc: recipients of the message",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      replyTo: {
        type: "array",
        description: "Reply-To addresses for the message",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      sender: {
        type: "object",
        description: "Account used to generate the message (emailAddress object)",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      receivedDateTime: {
        type: "dateTime",
        description: "Date and time the message was received",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      sentDateTime: {
        type: "dateTime",
        description: "Date and time the message was sent",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      isRead: {
        type: "boolean",
        description: "Whether the message has been read",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      isDraft: {
        type: "boolean",
        description: "Whether the message is a draft",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      hasAttachments: {
        type: "boolean",
        description: "Whether the message has attachments",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      importance: {
        type: "string",
        description: "Importance of the message: low, normal, or high",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      flag: {
        type: "object",
        description: "Follow-up flag status (flagStatus field)",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      categories: {
        type: "array",
        description: "Categories associated with the message",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      parentFolderId: {
        type: "string",
        description: "Unique identifier of the parent mail folder",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      conversationId: {
        type: "string",
        description: "Identifier of the conversation the message belongs to",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      webLink: {
        type: "string",
        description: "URL to open the message in Outlook on the web",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      inferenceClassification: {
        type: "string",
        description: "Classification of the message: focused or other",
        filterable: true,
        searchable: false,
        sortable: false,
      },
    },
  },

  event: {
    description: "Outlook calendar event",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the event",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      subject: {
        type: "string",
        description: "Subject or title of the event",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      body: {
        type: "object",
        description: "Body of the event (contentType + content)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      bodyPreview: {
        type: "string",
        description: "Plain text preview of the event body",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      start: {
        type: "object",
        description: "Start date/time and timezone of the event",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      end: {
        type: "object",
        description: "End date/time and timezone of the event",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      location: {
        type: "object",
        description: "Primary location of the event",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      locations: {
        type: "array",
        description: "All locations associated with the event",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      organizer: {
        type: "object",
        description: "Organizer of the event (emailAddress object)",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      attendees: {
        type: "array",
        description: "Collection of attendees for the event",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      isAllDay: {
        type: "boolean",
        description: "Whether the event lasts all day",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      isCancelled: {
        type: "boolean",
        description: "Whether the event has been cancelled",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      isOnlineMeeting: {
        type: "boolean",
        description: "Whether the event is an online meeting",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      onlineMeeting: {
        type: "object",
        description: "Online meeting details (joinUrl, conferenceId, etc.)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      onlineMeetingUrl: {
        type: "string",
        description: "URL to join the online meeting",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      recurrence: {
        type: "object",
        description: "Recurrence pattern and range for the event",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      responseStatus: {
        type: "object",
        description: "Current user's response status (response + time)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      showAs: {
        type: "string",
        description: "Free/busy status: free, tentative, busy, oof, workingElsewhere, unknown",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      sensitivity: {
        type: "string",
        description: "Sensitivity level: normal, personal, private, confidential",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      importance: {
        type: "string",
        description: "Importance of the event: low, normal, high",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      webLink: {
        type: "string",
        description: "URL to open the event in Outlook on the web",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the event was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
    },
  },

  calendar: {
    description: "Outlook calendar",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the calendar",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      name: {
        type: "string",
        description: "Name of the calendar",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      color: {
        type: "string",
        description: "Color theme of the calendar (auto, lightBlue, lightGreen, etc.)",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      isDefaultCalendar: {
        type: "boolean",
        description: "Whether this is the user's default calendar",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      canEdit: {
        type: "boolean",
        description: "Whether the user can write to the calendar",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      canShare: {
        type: "boolean",
        description: "Whether the user can share the calendar",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      owner: {
        type: "object",
        description: "Owner of the calendar (name + address)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  driveItem: {
    description: "OneDrive or SharePoint file or folder",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the drive item",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      name: {
        type: "string",
        description: "Name of the file or folder",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      size: {
        type: "number",
        description: "Size of the item in bytes",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the item was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      lastModifiedDateTime: {
        type: "dateTime",
        description: "Date and time the item was last modified",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      webUrl: {
        type: "string",
        description: "URL to access the item in a browser",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      createdBy: {
        type: "object",
        description: "Identity of the user/app that created the item",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      lastModifiedBy: {
        type: "object",
        description: "Identity of the user/app that last modified the item",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      parentReference: {
        type: "object",
        description: "Parent folder information (driveId, id, path)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      file: {
        type: "object",
        description: "File metadata if the item is a file (mimeType, hashes)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      folder: {
        type: "object",
        description: "Folder metadata if the item is a folder (childCount)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      "@microsoft.graph.downloadUrl": {
        type: "string",
        description: "Pre-authenticated short-lived download URL for the file content",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  drive: {
    description: "OneDrive or SharePoint document library",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the drive",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      name: {
        type: "string",
        description: "Name of the drive",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      driveType: {
        type: "string",
        description: "Type of drive: personal, business, or documentLibrary",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      owner: {
        type: "object",
        description: "Owner of the drive (user or group identity)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      quota: {
        type: "object",
        description: "Storage quota information (total, used, remaining, state)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  site: {
    description: "SharePoint site",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the site",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Display name of the site",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      name: {
        type: "string",
        description: "URL-safe name of the site",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      webUrl: {
        type: "string",
        description: "Full URL of the site",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      siteCollection: {
        type: "object",
        description: "Site collection metadata (hostname, root)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      root: {
        type: "object",
        description: "Root resource if the site is the root of the site collection",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  list: {
    description: "SharePoint list",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the list",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Display name of the list",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      description: {
        type: "string",
        description: "Description of the list",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      list: {
        type: "object",
        description: "List-specific metadata (template, contentTypesEnabled, hidden)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the list was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      lastModifiedDateTime: {
        type: "dateTime",
        description: "Date and time the list was last modified",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      webUrl: {
        type: "string",
        description: "URL to access the list in a browser",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  listItem: {
    description: "SharePoint list item",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the list item",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the item was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      lastModifiedDateTime: {
        type: "dateTime",
        description: "Date and time the item was last modified",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      fields: {
        type: "object",
        description: "Column values of the list item (dynamic, depends on list schema)",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      contentType: {
        type: "object",
        description: "Content type information for the list item",
        filterable: true,
        searchable: false,
        sortable: false,
      },
    },
  },

  todoTask: {
    description: "Microsoft To Do task",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the task",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      title: {
        type: "string",
        description: "Title of the task",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      body: {
        type: "object",
        description: "Body/notes of the task (contentType + content)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      status: {
        type: "string",
        description: "Status of the task: notStarted, inProgress, completed, waitingOnOthers, deferred",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      importance: {
        type: "string",
        description: "Importance of the task: low, normal, high",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      isReminderOn: {
        type: "boolean",
        description: "Whether a reminder is set for the task",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      dueDateTime: {
        type: "object",
        description: "Due date and timezone of the task",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      completedDateTime: {
        type: "object",
        description: "Date and timezone when the task was completed",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the task was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      lastModifiedDateTime: {
        type: "dateTime",
        description: "Date and time the task was last modified",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      startDateTime: {
        type: "object",
        description: "Start date and timezone of the task",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      categories: {
        type: "array",
        description: "Categories associated with the task",
        filterable: true,
        searchable: false,
        sortable: false,
      },
    },
  },

  todoTaskList: {
    description: "Microsoft To Do task list",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the task list",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Display name of the task list",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      isOwner: {
        type: "boolean",
        description: "Whether the current user owns the task list",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      isShared: {
        type: "boolean",
        description: "Whether the task list is shared with other users",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      wellknownListName: {
        type: "string",
        description: "Well-known list name if applicable: defaultList, flaggedEmails, unknownFutureValue",
        filterable: true,
        searchable: false,
        sortable: false,
      },
    },
  },

  plannerTask: {
    description: "Microsoft Planner task",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the planner task",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      title: {
        type: "string",
        description: "Title of the planner task",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      planId: {
        type: "string",
        description: "Identifier of the plan the task belongs to",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      bucketId: {
        type: "string",
        description: "Identifier of the bucket the task belongs to",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      percentComplete: {
        type: "number",
        description: "Percentage of task completion (0–100)",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      dueDateTime: {
        type: "dateTime",
        description: "Due date and time of the task in UTC",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      startDateTime: {
        type: "dateTime",
        description: "Start date and time of the task in UTC",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the task was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      assignments: {
        type: "object",
        description: "Set of assignees (keyed by user ID with assignment details)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      priority: {
        type: "number",
        description: "Priority of the task (0=urgent, 1=important, 2=medium, 3+=low)",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      orderHint: {
        type: "string",
        description: "Hint used to order items of this type in a list view",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      conversationThreadId: {
        type: "string",
        description: "Thread ID of the conversation on the task in the group",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      "@odata.etag": {
        type: "string",
        description: "ETag for concurrency control when updating the task",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  plannerPlan: {
    description: "Microsoft Planner plan",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the plan",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      title: {
        type: "string",
        description: "Title of the plan",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      owner: {
        type: "string",
        description: "ID of the group that owns the plan",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the plan was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      createdBy: {
        type: "object",
        description: "Identity of the user who created the plan",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  plannerBucket: {
    description: "Microsoft Planner bucket (column in a plan board)",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the bucket",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      name: {
        type: "string",
        description: "Name of the bucket",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      planId: {
        type: "string",
        description: "Identifier of the plan the bucket belongs to",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      orderHint: {
        type: "string",
        description: "Hint used to order buckets in a list view",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  team: {
    description: "Microsoft Teams team",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the team",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Display name of the team",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      description: {
        type: "string",
        description: "Description of the team",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      isArchived: {
        type: "boolean",
        description: "Whether the team is archived",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      webUrl: {
        type: "string",
        description: "URL to open the team in Microsoft Teams",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  channel: {
    description: "Microsoft Teams channel",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the channel",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Display name of the channel",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      description: {
        type: "string",
        description: "Description of the channel",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      membershipType: {
        type: "string",
        description: "Membership type: standard, private, shared, or unknownFutureValue",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      webUrl: {
        type: "string",
        description: "URL to open the channel in Microsoft Teams",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  chatMessage: {
    description: "Microsoft Teams or chat message",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the message",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      body: {
        type: "object",
        description: "Body of the message (contentType + content)",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      from: {
        type: "object",
        description: "Sender identity (user, application, or device)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the message was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      lastModifiedDateTime: {
        type: "dateTime",
        description: "Date and time the message was last edited",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      importance: {
        type: "string",
        description: "Importance of the message: normal, high, urgent",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      messageType: {
        type: "string",
        description: "Type of message: message, chatEvent, typing, systemEventMessage, unknownFutureValue",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      webLink: {
        type: "string",
        description: "URL to the message in Microsoft Teams",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  chat: {
    description: "Microsoft Teams chat (1:1, group, or meeting chat)",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the chat",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      topic: {
        type: "string",
        description: "Topic/subject of the chat (may be null for 1:1 chats)",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      chatType: {
        type: "string",
        description: "Type of chat: oneOnOne, group, or meeting",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      createdDateTime: {
        type: "dateTime",
        description: "Date and time the chat was created",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      lastUpdatedDateTime: {
        type: "dateTime",
        description: "Date and time of the last activity in the chat",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      members: {
        type: "array",
        description: "Members of the chat (conversationMember collection)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  presence: {
    description: "Microsoft Teams user presence status",
    properties: {
      id: {
        type: "string",
        description: "User ID for the presence record",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      availability: {
        type: "string",
        description: "Base availability: Available, Busy, DoNotDisturb, BeRightBack, Away, Offline, etc.",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      activity: {
        type: "string",
        description: "Supplemental activity information: InACall, InAConferenceCall, Presenting, etc.",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      statusMessage: {
        type: "object",
        description: "User-set status message (message, expiryDateTime, etc.)",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  user: {
    description: "Azure AD / Microsoft 365 user profile",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the user",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Full display name of the user",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      mail: {
        type: "string",
        description: "SMTP email address of the user",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      userPrincipalName: {
        type: "string",
        description: "User principal name (UPN), typically the sign-in name",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      givenName: {
        type: "string",
        description: "First name of the user",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      surname: {
        type: "string",
        description: "Last name of the user",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      jobTitle: {
        type: "string",
        description: "Job title of the user",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      department: {
        type: "string",
        description: "Department the user belongs to",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      officeLocation: {
        type: "string",
        description: "Office location of the user",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      mobilePhone: {
        type: "string",
        description: "Mobile phone number of the user",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      businessPhones: {
        type: "array",
        description: "Business phone numbers of the user",
        filterable: false,
        searchable: false,
        sortable: false,
      },
    },
  },

  mailFolder: {
    description: "Outlook mail folder",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the mail folder",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Display name of the mail folder",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      totalItemCount: {
        type: "number",
        description: "Total number of items in the folder",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      unreadItemCount: {
        type: "number",
        description: "Number of unread items in the folder",
        filterable: true,
        searchable: false,
        sortable: true,
      },
      parentFolderId: {
        type: "string",
        description: "Unique identifier of the parent folder",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      childFolderCount: {
        type: "number",
        description: "Number of immediate child folders",
        filterable: true,
        searchable: false,
        sortable: true,
      },
    },
  },

  contact: {
    description: "Outlook personal contact",
    properties: {
      id: {
        type: "string",
        description: "Unique identifier of the contact",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      displayName: {
        type: "string",
        description: "Full display name of the contact",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      givenName: {
        type: "string",
        description: "First name of the contact",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      surname: {
        type: "string",
        description: "Last name of the contact",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      emailAddresses: {
        type: "array",
        description: "Email addresses of the contact (name + address pairs)",
        filterable: false,
        searchable: true,
        sortable: false,
      },
      businessPhones: {
        type: "array",
        description: "Business phone numbers of the contact",
        filterable: false,
        searchable: false,
        sortable: false,
      },
      mobilePhone: {
        type: "string",
        description: "Mobile phone number of the contact",
        filterable: true,
        searchable: false,
        sortable: false,
      },
      companyName: {
        type: "string",
        description: "Company the contact works for",
        filterable: true,
        searchable: true,
        sortable: true,
      },
      jobTitle: {
        type: "string",
        description: "Job title of the contact",
        filterable: true,
        searchable: true,
        sortable: true,
      },
    },
  },
};
